packages:
  - apps/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - "@nestjs/core"
  - "prisma"
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
